[build-system]
requires = ["setuptools>=69"]
build-backend = "setuptools.build_meta"

[project]
name = "ott-movies-be"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "fastapi==0.116.1",
    "sqlalchemy==2.0.43",
    "pydantic-settings==2.10.1",
    "PyJWT==2.10.1",
    "python-dotenv==1.1.1",
]

[project.optional-dependencies]
local = [
    "uvicorn[standard]==0.35.0",
    "alembic==1.16.4",
]
postgres = [
    "psycopg[binary]==3.2.9",
    "alembic==1.16.4",
]

[dependency-groups]
dev = [
    "workers-py",
    "workers-runtime-sdk",
]

[tool.setuptools.package-dir]
"" = "src"

[tool.setuptools.packages.find]
where = ["src"]
include = ["app*"]
